### ISSUE TITLE
IllegalStateException: cannot stop. Player in mState ERROR

### ISSUE THREAD

**Issue by neestell** [danylovolokh/VideoPlayerManager#11]
Hi danylovolokh!
I found a stable crash for a MediaPlayer when I scroll fast up/down 6 videos. Please help.

 java.lang.IllegalStateException: cannot stop. Player in mState ERROR at com.volokh.danylo.video_player_manager.ui.MediaPlayerWrapper.stop(MediaPlayerWrapper.java:433)
at com.volokh.danylo.video_player_manager.ui.VideoPlayerView.stop(VideoPlayerView.java:186)
at com.volokh.danylo.video_player_manager.player_messages.Stop.performAction(Stop.java:19)
at com.volokh.danylo.video_player_manager.player_messages.PlayerMessage.runMessage(PlayerMessage.java:40) at com.volokh.danylo.video_player_manager.MessagesHandlerThread$1.run(MessagesHandlerThread.java:61)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                 at java.lang.Thread.run(Thread.java:841)

**Comment by danylovolokh** [comment]
Hi, I find this as a duplicate.

There is no fix for it for now.
Please find the explanation here : https://github.com/danylovolokh/VideoPlayerManager/issues/6

**Comment by neestell** [comment]
Thanks for the answer!
