### ISSUE TITLE
How to pass String path to the VideoPlayerView

### ISSUE THREAD

**Issue by Cruzbenhur** [danylovolokh/VideoPlayerManager#30]
I want to pass the video url to the videoplayerview dont know where to pass it help me out...

**Comment by RockyLin** [comment]
Eventually, it's AssetVideoItem's method that handles the video from url
public void playNewVideo(MetaData currentItemMetaData, VideoPlayerView player, VideoPlayerManager<MetaData> videoPlayerManager){
videoPlayerManager.playNewVideo(currentItemMetaData, player, videoUrl);
}

**Comment by ShahbazA** [comment]
Made this method for playing from url in Recylerview:

public static BaseVideoItem playFromUrl(String assetName, String mUrl, Activity activity, VideoPlayerManager<MetaData> videoPlayerManager, int imageResource) throws IOException {
        return new AssetVideoItem(assetName, videoPlayerManager, Picasso.with(activity), mUrl, imageResource);
    }

gives exception and wont play video:

E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                                                                        Process: com.testingvideoplayer, PID: 17436
                                                                        java.lang.RuntimeException: java.io.IOException: setDataSource failed.: status=0x80000000
                                                                            at com.volokh.danylo.video_player_manager.ui.VideoPlayerView.setDataSource(VideoPlayerView.java:263)
                                                                            at com.volokh.danylo.video_player_manager.player_messages.SetUrlDataSourceMessage.performAction(SetUrlDataSourceMessage.java:24)
                                                                            at com.volokh.danylo.video_player_manager.player_messages.PlayerMessage.runMessage(PlayerMessage.java:40)
                                                                            at com.volokh.danylo.video_player_manager.MessagesHandlerThread$1.run(MessagesHandlerThread.java:61)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.io.IOException: setDataSource failed.: status=0x80000000
                                                                            at android.media.MediaPlayer.nativeSetDataSource(Native Method)
                                                                            at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1071)
                                                                            at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1032)
                                                                            at com.volokh.danylo.video_player_manager.ui.MediaPlayerWrapper.setDataSource(MediaPlayerWrapper.java:164)
                                                                            at com.volokh.danylo.video_player_manager.ui.VideoPlayerView.setDataSource(VideoPlayerView.java:259)
                                                                            at com.volokh.danylo.video_player_manager.player_messages.SetUrlDataSourceMessage.performAction(SetUrlDataSourceMessage.java:24) 
                                                                            at com.volokh.danylo.video_player_manager.player_messages.PlayerMessage.runMessage(PlayerMessage.java:40) 
                                                                            at com.volokh.danylo.video_player_manager.MessagesHandlerThread$1.run(MessagesHandlerThread.java:61) 
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                            at java.lang.Thread.run(Thread.java:818)

**Comment by Bhavesh-Moradiya** [comment]
Hi, I am also having problem in that how to pass string to list the video.

Example:
/storage/emulated/0/Camera/video_20181005_120633.mp4"
/storage/emulated/0/Camera/video_20181005_120621.mp4"
/storage/emulated/0/Camera/video_20181005_120609.mp4" 

I have this 3 string that I want to list in my project but library seems to complex for me, Please help me how can I pass these string in adapter @Cruzbenhur @danylovolokh

Thank You
