### ISSUE TITLE
when I  add header in listview It crash 

### ISSUE THREAD

**Issue by anjiao** [danylovolokh/VideoPlayerManager#39]
java.lang.IndexOutOfBoundsException: Invalid index 5, size is 5
                                                       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                       at java.util.ArrayList.get(ArrayList.java:308)
                                                       at com.volokh.danylo.visibility_utils.calculator.SingleListViewItemActiveCalculator.topToBottomMostVisibleItem(SingleListViewItemActiveCalculator.java:206)
                                                       at com.volokh.danylo.visibility_utils.calculator.SingleListViewItemActiveCalculator.calculateMostVisibleItem(SingleListViewItemActiveCalculator.java:179)
                                                       at com.volokh.danylo.visibility_utils.calculator.SingleListViewItemActiveCalculator.onScrollStateIdle(SingleListViewItemActiveCalculator.java:159)

**Comment by 88567free** [comment]
I also encountered this problem

**Comment by prathameshtal** [comment]
Hi, anyone of you have added any fix for this issue?

**Comment by libaoyou2011** [comment]
I also meet this problem about add a header in listview, anybody can solve this problem?
