### ISSUE TITLE
cannot stop. Player in mState ERROR

### ISSUE THREAD

**Issue by alaaodeh95** [danylovolokh/VideoPlayerManager#59]
02-18 12:22:11.787 29632-29959/? E/AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
                                                   Process: com.maddarek.guzel, PID: 29632
                                                   java.lang.IllegalStateException: cannot stop. Player in mState ERROR
                                                       at com.volokh.danylo.video_player_manager.ui.MediaPlayerWrapper.stop(MediaPlayerWrapper.java:433)
                                                       at com.volokh.danylo.video_player_manager.ui.VideoPlayerView.stop(VideoPlayerView.java:186)
                                                       at com.volokh.danylo.video_player_manager.player_messages.Stop.performAction(Stop.java:19)
                                                       at com.volokh.danylo.video_player_manager.player_messages.PlayerMessage.runMessage(PlayerMessage.java:40)
                                                       at com.volokh.danylo.video_player_manager.MessagesHandlerThread$1.run(MessagesHandlerThread.java:61)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:841)

**Comment by hasanmumin** [comment]
any solution ?

**Comment by dayanithi06** [comment]
@hasanmumin  I also received the error because i did not load the correct file or url try to load the correct file format or the url . especially check weather u are loading it in the image. I am not sure is this is the case for you. thx
