### ISSUE TITLE
It should be called in main thread

### ISSUE THREAD

**Issue by Shivamall** [danylovolokh/VideoPlayerManager#84]
Process: com.example.videolist, PID: 21578
                                                                       java.lang.RuntimeException: this should be called in Main Thread
                                                                           at com.volokh.danylo.video_player_manager.ui.MediaPlayerWrapper.onVideoSizeChanged(MediaPlayerWrapper.java:214)
                                                                           at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3328)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by Ajk2rxKamehameha** [comment]
Did you find any answer?

**Comment by itzharDev** [comment]
same problem

**Comment by paolomoschini** [comment]
In `MediaPlayerWrapper ` change this:

```
  private boolean inUiThread() {
        return Thread.currentThread().getId() == 1;
    }
```

with this:

```
private boolean inUiThread() {
   return Thread.currentThread() == Looper.getMainLooper().getThread();
}
```
